title: LGIAS
email: inquiries@lgias.com
description: >-
  LGIAS builds apps and connected hardware. Today, we build for water polo.
theme: minima
header_pages:
  - wpboard/index.md
  - wpcam/index.md
  - wprefassist/index.md
  - contact/index.md
